### ISSUE TITLE
Not available in Maven Central?

### ISSUE THREAD

**Issue by keesvandieren** [otto-de/enhanced-wickettester#2]
Hi,

The artifacts seems to be not available in Maven Central.

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22de.otto%22

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22enhanced-wickettester%22

**Comment by BeneStem** [comment]
it is released on sonatype

**Comment by keesvandieren** [comment]
I can find an old snapshot (https://oss.sonatype.org/content/repositories/snapshots/de/otto/enhanced-wickettester/ ) but no release.

**Comment by BeneStem** [comment]
i am not sure if there has been a release ever.
let me check that with my colleagues.
we use that 0.1-SNAPSHOT version in our wicket project since a few years back :D

**Comment by sonata82** [comment]
No plans for a release build?

**Comment by BeneStem** [comment]
we could make a release version of the current snapshot - havnt done anything on this project for a long time. its currently available on sonatype as a very stable snapshot :-)

**Comment by sonata82** [comment]
Would be great to have a release version, no need for changes! 

Would save me the hassle of inserting a separate repo into the pom, avoid checking for a new snapshot at every maven execution and its kind of frowned upon to have a release version of an application depending on snapshots. In this case only being in test scope and very stable, I know, but it's just gives my colleagues a reason to say no :grin:

**Comment by BeneStem** [comment]
Ok. No Problem.
I will try to build a release version until tomorrow.
Have to ask a colleague for the credentials xD
Maybe it'll take a little longer, not sure yet, sorry...

**Comment by stefan42** [comment]
Hey,
we've just released the 0.2 version in sonatype nexus.
It is basically the last 0.1-SNAPSHOT version

**Comment by sonata82** [comment]
Looks good, thank you very much!
